title: ipazzxyz
title_separator: |
url: https://ipazz.xyz
repository: ipazzxyz/ipazzxyz.github.io
atom_feed:
  hide: true
search: true
locale: ru

theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

include: [_pages]